### ISSUE TITLE
Update issue with persistent storage

### ISSUE THREAD

**Issue by AlexandreRio** [garywiz/docker-grav#10]
Hi,

I want to run grav with a persistent storage but when I try to update it I got an AJAX error (invalid answer) and a `mkdir() permission denied` error.

Here is how I run it:

```
$ mkdir grav/
$ docker run -p 80:8080 -p 443:8443 -d -v /home/user/grav:/apps/var garywiz/docker-grav --create-user user:/apps/var
```

Any thoughts?

Thanks

**Comment by ghost** [comment]
You can not upgrade Grav using the admin interface; the author explains why here https://github.com/garywiz/docker-grav/issues/7

**Comment by AlexandreRio** [comment]
I don't remember having opened this bug…
I actually fixed my setup by running the webserver(nginx) with the same uid/gid as the owner of the shared volume.
I'm closing the issue since I wouldn't say if a patch fix it or not.
