### ISSUE TITLE
No license information found

### ISSUE THREAD

**Issue by ikstream** [garywiz/docker-grav#2]
Hi,
i really like your work, but could find no licensing information.
Do you plan to put one into your project, or did i simply miss the license?

Best regards

**Comment by garywiz** [comment]
Thanks for pointing that out!  I use the Apache license for everything.  I will add it to the build in a day or so when I get a chance.

**Comment by garywiz** [comment]
I finally got around to this!  Sorry for the delay.  The Apache license is now prominent in the build root as well as the README.  I've also upgraded to the latest Grav and pushed the image to Docker Hub.

**Comment by ikstream** [comment]
Thank you very much
